version: '3'
volumes: 
    udata:
    ndata:
    rdata:
    pgadmin-data:
services: 
    udb: 
        container_name: udb
        image: postgres
        environment: 
            POSTGRES_DB: ${ACCOUNT_DB}
            POSTGRES_USER: ${ACCOUNT_DEV_USER}
            POSTGRES_PASSWORD: ${POSTGRES_DEV_PASSWORD}
        ports:
            - ${ACCOUNT_DB_PORT}:5432
        volumes:
            - udata:/var/lib/postgresql/data
        networks:
            - security
    db:
        container_name: newsdb
        image: postgres
        environment: 
            POSTGRES_DB: ${NEWS_DB}
            POSTGRES_USER: ${NEWS_DB_USER}
            POSTGRES_PASSWORD: ${POSTGRES_DEV_PASSWORD}
        command: -p 5433
        expose: 
            - '5433'
        ports:
            - ${NEWS_DB_PORT}:5433
        volumes:
            - ndata:/var/lib/postgresql/data
        networks:
            - basic
    cache:
        container_name: cache
        image: redis:alpine
        command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
        hostname: redis
        networks:
            - redis-net
        volumes:
            - rdata:/data
        networks:
            - basic
    app:
        container_name: goapp
        build: .
        command: ./wait-for-it.sh udb:5432 -- go run api/main.go
        volumes:
            - .:/go/src/app
        ports:
            - "8080:8010"
        env_file: 
            - .env
        depends_on:
            - udb
            - db
        links:
            - udb
            - db
        networks:
            - basic
            - security

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: pwdpwd
        ports:
            - "5050:80"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        links:
            - udb
        depends_on:
            - udb
        networks:
            -  security

networks:
    basic:
        driver: bridge
    security:
        driver: bridge